# Permalinks
permalink:        /:title

# Setup
title:            Αντώνης Νάνος
tagline:          Λογιστικό - Φοροτεχνικό Γραφείο
description:      Λογιστικό - Φοροτεχνικό Γραφείο
url:              https://ananos.gr
baseurl:          /
rawurl:	          
# Add this and create headline.html in _includes directory
# headline: true         
# Add your google_analytics ID if you need it
# google_analytics: 

# Pagination number
paginate:         10

# category page
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
